services:
  postgres:
    container_name: ignite-project-05-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ignite-project-05
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
  cache:
    container_name: ignite-project-05-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data